FROM node:16.18-alpine

WORKDIR /usr/src/node-app

ARG MONGODB_URL
ARG JWT_SECRET
ARG JWT_ACCESS_EXPIRATION_MINUTES
ARG JWT_REFRESH_EXPIRATION_DAYS
ARG JWT_RESET_PASSWORD_EXPIRATION_MINUTES
ARG JWT_VERIFY_EMAIL_EXPIRATION_MINUTES

ARG CLIENT_ID
ARG CLIENT_SECRET
ARG REDIRECT_URL
ARG API_KEY

ENV MONGODB_URL=${MONGODB_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_ACCESS_EXPIRATION_MINUTES=${JWT_ACCESS_EXPIRATION_MINUTES}
ENV JWT_REFRESH_EXPIRATION_DAYS=${JWT_REFRESH_EXPIRATION_DAYS}
ENV JWT_RESET_PASSWORD_EXPIRATION_MINUTES=${JWT_RESET_PASSWORD_EXPIRATION_MINUTES}
ENV JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=${JWT_VERIFY_EMAIL_EXPIRATION_MINUTES}

ENV CLIENT_ID=${CLIENT_ID}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV REDIRECT_URL=${REDIRECT_URL}
ENV API_KEY=${API_KEY}

COPY package*.json ./

RUN npm install 

COPY . .

ENV NODE_ENV=development
ENV PORT=3000

EXPOSE 3000

CMD ["node", "src/index.js"]