FROM node:18

ARG PORT
ARG NODE_ENV
ARG MONGODB_URL
ARG JWT_SECRET
ARG JWT_ACCESS_EXPIRATION_MINUTES
ARG JWT_REFRESH_EXPIRATION_DAYS
ARG JWT_RESET_PASSWORD_EXPIRATION_MINUTES
ARG JWT_VERIFY_EMAIL_EXPIRATION_MINUTES

ARG CLIENT_ID
ARG CLIENT_SECRET
ARG REDIRECT_URL
ARG API_KEY

ENV PORT=${PORT}
ENV NODE_ENV=${NODE_ENV}
ENV MONGODB_URL=${MONGODB_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_ACCESS_EXPIRATION_MINUTES=${JWT_ACCESS_EXPIRATION_MINUTES}
ENV JWT_REFRESH_EXPIRATION_DAYS=${JWT_REFRESH_EXPIRATION_DAYS}
ENV JWT_RESET_PASSWORD_EXPIRATION_MINUTES=${JWT_RESET_PASSWORD_EXPIRATION_MINUTES}
ENV JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=${JWT_VERIFY_EMAIL_EXPIRATION_MINUTES}

ENV CLIENT_ID=${CLIENT_ID}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV REDIRECT_URL=${REDIRECT_URL}
ENV API_KEY=${API_KEY}

RUN mkdir -p /usr/src/node-app && chown -R node:node /usr/src/node-app

WORKDIR /usr/src/node-app

COPY package.json yarn.lock ./

USER node

RUN yarn install --pure-lockfile

COPY --chown=node:node . .

EXPOSE 8080

CMD ["node", "src/index.js"]
