name: Deploy to Cloud Run

  on:
    push:
        branches:
            - master

  jobs:
    deploy:
        runs-on: ubuntu-latest

        steps: 
          - name: Checkout code 
            uses: actions/checkout@v2
        
          - name: Set Up Cloud SDK
            uses: google-github-actions/setup-gcloud@v0.2.0
            with: 
                project_id: bangkit-capstone-kalmakasa
                service_account_key: ${{secrets.GCLOUD_AUTH}}

          - name: Configure Docker to use gcloud 
            run: |
                gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

          - name: Set Environment Variables
            run: |
                echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
                echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV
                echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV
                echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
                echo "JWT_ACCESS_EXPIRATION_MINUTES=${{ secrets.JWT_ACCESS_EXPIRATION_MINUTES }}" >> $GITHUB_ENV
                echo "JWT_REFRESH_EXPIRATION_DAYS=${{ secrets.JWT_REFRESH_EXPIRATION_DAYS }}" >> $GITHUB_ENV
                echo "JWT_RESET_PASSWORD_EXPIRATION_MINUTES=${{ secrets.JWT_RESET_PASSWORD_EXPIRATION_MINUTES }}" >> $GITHUB_ENV
                echo "JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=${{ secrets.JWT_VERIFY_EMAIL_EXPIRATION_MINUTES }}" >> $GITHUB_ENV
                echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
                echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
                echo "REDIRECT_URL=${{ secrets.REDIRECT_URL }}" >> $GITHUB_ENV
                echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
                
            
          - name: Build and Push Docker Image 
            run: |
                export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
                export IMAGE_NAME=asia-southeast2-docker.pkg.dev/bangkit-capstone-kalmakasa/cloud-run-source-deploy/kalmakasa-be:${IMAGE_TAG}
                docker build  --build-arg PORT=$PORT \
                              --build-arg NODE_ENV=$NODE_ENV \
                              --build-arg MONGODB_URL=$MONGODB_URL \
                              --build-arg JWT_SECRET=$JWT_SECRET \
                              --build-arg JWT_ACCESS_EXPIRATION_MINUTES=$JWT_ACCESS_EXPIRATION_MINUTES \
                              --build-arg JWT_REFRESH_EXPIRATION_DAYS=$JWT_REFRESH_EXPIRATION_DAYS \
                              --build-arg JWT_RESET_PASSWORD_EXPIRATION_MINUTES=$JWT_RESET_PASSWORD_EXPIRATION_MINUTES \
                              --build-arg JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=$JWT_VERIFY_EMAIL_EXPIRATION_MINUTES \
                              --build-arg CLIENT_ID=$CLIENT_ID \
                              --build-arg CLIENT_SECRET=$CLIENT_SECRET \
                              --build-arg REDIRECT_URL=$REDIRECT_URL \
                              --build-arg API_KEY=$API_KEY \
                              -t ${IMAGE_NAME} .
                docker push ${IMAGE_NAME}

          - name: Deploy to Cloud Run
            run: |
                export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
                export IMAGE_NAME=asia-southeast2-docker.pkg.dev/bangkit-capstone-kalmakasa/cloud-run-source-deploy/kalmakasa-be:${IMAGE_TAG}
                gcloud run deploy kalmakasa-be --image ${IMAGE_NAME} --region asia-southeast2 --allow-unauthenticated
           